{% set setup_data = load_setup_py_data() %}

package:
  name: django-sql-explorer
  version: {{ setup_data.get('version') }}

source:
  git_url: ../

build:
  number: {{ environ.get("PKG_BUILDNUM", 0) }}

{%
  set deps = [
    "django>=1.7.0",
    "sqlparse>=0.1.18",
    "unicodecsv>=0.14.1",
    "six>=1.10.0",
]
%}

requirements:
  build:
    - python {{ python }}
    - setuptools
    {% for dep in deps %}
    - {{ dep }}
    {% endfor %}

  run:
    - python {{ python }}
    {% for dep in deps %}
    - {{ dep }}
    {% endfor %}

test:
  imports:
    - explorer

about:
  home: {{ setup_data.get('url') }}
  license: {{ setup_data.get('license') }}
  summary: {{ setup_data.get('description') }}
